before:
  hooks:
    - go generate -v ./...
builds:
- id: dazzle
  env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X github.com/gitpod-io/dazzle/cmd/core.version={{.Version}}-{{.ShortCommit}}
  goos:
  - darwin
  - linux
- id: dazzle-util
  env:
  - CGO_ENABLED=0
  main: main-util.go
  binary: dazzle-util
  flags:
    - -tags=util
  ldflags:
  - -s -w -X github.com/gitpod-io/dazzle/cmd/util.version={{.Version}}-{{.ShortCommit}}
  goos:
  - darwin
  - linux
archives:
- id: dazzle
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
  builds:
  - dazzle
- id: dazzle-util
  files:
  - "none*"
  format: binary
  builds:
  - dazzle-util
  replacements:
    darwin: Darwin
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  prerelease: auto
dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    dockerfile: Dockerfile
    image_templates:
    - "ghcr.io/gitpod-io/dazzle:{{ .Tag }}"
    extra_files:
    - README.md
